version: '3.1'

networks:
  corp:
    driver: bridge

volumes:
  database_data:
    driver: local

services:
  api:
    container_name: lazy-api
    networks:
      - corp
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - "3333:3333"
  lazy-app:
    container_name: lazy-app
    networks:
      - corp
    build:
      context: .
      dockerfile: client.dockerfile
    ports:
      - "4200:4200"
  db:
    image: postgres
    restart: always
    networks:
      - corp
    environment:
      POSTGRES_PASSWORD: example
