version: '3.1'

volumes:
  pg_data:

networks:
  corp:

services:
  api:
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - 3000:3000
    networks:
      - corp
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    volumes:
      - "./apps:/app/apps:ro"
      - "./libs:/app/libs:ro"
  app:
    build:
      context: .
      dockerfile: client.dockerfile
    ports:
      - 4200:4200
    networks:
      - corp
    volumes:
      - "./apps:/app/apps:ro"
      - "./libs:/app/libs:ro"
  postgres:
    image: postgres
    restart: always
    networks:
      - corp
    environment:
      POSTGRES_DB: bazel-nx-example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
